export const azureConfigs = {
  STORAGE: {
    CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING || '',
    CONNECTION_TIMEOUT: process.env.AZURE_STORAGE_CONNECTION_TIMEOUT
      ? +process.env.AZURE_STORAGE_CONNECTION_TIMEOUT
      : 600,
    DATASET_CONTAINER_NAME: process.env.AZURE_DATASET_CONTAINER_NAME || '',
    PUBLIC_CONTAINER_NAME: process.env.AZURE_PUBLIC_CONTAINER_NAME || '',
    ORIGINAL_CONTAINER_NAME: process.env.AZURE_ORIGINAL_CONTAINER_NAME || '',
    EXPORT_MODEL_CONTAINER_NAME:
      process.env.AZURE_EXPORT_MODEL_CONTAINER_NAME || '',
    IMPORT_MODEL_CONTAINER_NAME:
      process.env.AZURE_IMPORT_MODEL_CONTAINER_NAME || '',
  },
  AKS: {
    PREFIX: process.env.AKS_PREFIX || '',
    TOKEN: process.env.AKS_TOKEN || '',
    NODE_TLS_REJECT_UNAUTHORIZED: process.env.NODE_TLS_REJECT_UNAUTHORIZED,
    TRAINING_IMAGE: process.env.AKS_TRAINING_IMAGE,
    TRAINING_IMAGE_SECRET: process.env.AKS_TRAINING_IMAGE_SECRET,
    CLUSTER_NAME: process.env.AKS_CLUSTER_NAME || '',
    CLUSTER_SERVER: process.env.AKS_CLUSTER_SERVER || '',
    CLUSTER_CA_DATA: process.env.AKS_CLUSTER_CA_DATA || '',
    USER_NAME: process.env.AKS_USER_NAME || '',
    CERT_DATA: process.env.AKS_CERT_DATA || '',
    KEY_DATA: process.env.AKS_KEY_DATA || '',
    NAMESPACE: process.env.AKS_NAMESPACE || '',
  },
  SERVICE_BUS: {
    CONNECTION_STRING: process.env.AZURE_SERVICE_BUS_CONNECTION_STRING || '',
  },
  WEB_PUB_SUB: {
    CONNECTION_STRING: process.env.AZURE_WEB_PUB_SUB_CONNECTION_STRING || '',
    HUB_NAME: process.env.AZURE_WEB_PUB_SUB_HUB_NAME || '',
  },
};
